WebApp/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Services;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class ContactsController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        private readonly CommentService _commentService;

        public ContactsController(CommentService commentService)
        {
            _commentService = commentService;
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactsViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _commentService.PostCommentAsync(model);

                if (result.StatusCode == System.Net.HttpStatusCode.Created)
                {
                    ModelState.Clear();
                    model = new ContactsViewModel()
                    {
                        ConfirmString = "Your comment has been posted!"
                    };
                    return View(model);
                }

                model.ConfirmString = "Something went wrong, try again.";

            }

            return View(model);
        }
    }
}

WebApp/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Services;

namespace WebApp.Controllers;

public class ProductsController : Controller
{
    private readonly ProductService _productService;

    public ProductsController(ProductService productService)
    {
        _productService = productService;
    }

    public async Task<IActionResult> Details(int id)
    {
        return View(await _productService.GetProductAsync(id));
    }
}

WebApp/Views/Shared/Partials/_Collection.cshtml
<section class="collection-grid">
    <div class="container">
        <div class="title">Featured Products</div>
        <div class="item-collection">
            @*Här ska det vara 8st collection items*@
            @for (int i = 0; i < 8; i++)
            {
                <partial name="~/Views/Shared/Partials/_CollectionItem.cshtml" />
            }
        </div>
    </div>
</section>

WebApp/Views/Shared/Partials/_CollectionGrid.cshtml
@model IEnumerable<ProductModel>

<section class="collection-grid">
    <div class="container">
        <div class="title">@ViewData["CollectionTitle"]</div>

        <div class="item-collection">

            @foreach (var item in Model)
            {
                <partial name="~/Views/Shared/Partials/_CollectionItem.cshtml" model="item" />
            }
        </div>
    </div>
</section>

WebApp/Views/Shared/Partials/_CollectionItem.cshtml
@model ProductModel;

<div class="item">
    <div class="image-section">
        <img src="@Model.ImageUrl" alt="@Model.Title" />
        <div class="menu">
            <div class="icons">
                <button class="link"><i class="fa-regular fa-code-compare"></i></button>
                <button class="link"><i class="fa-regular fa-heart"></i></button>
                <button class="link"><i class="fa-regular fa-bag-shopping"></i></button>
            </div>
            <a class="btn-theme" asp-controller="Products" asp-action="Details" asp-route-id="@Model.Id">QUICK VIEW</a>
        </div>
    </div>
    <div class="body-section">
        <div class="name">@Model.Title</div>
        <partial name="~/Views/Shared/Partials/_StarRating.cshtml" model="@Model.StarRating" />
        <div class="price">@Model.Price kr</div>
    </div>
</div>

WebApp/Views/Shared/Partials/_Footer.cshtml
<footer>
    <hr class="footer-hr" />
    <div class="footer-container">
        <a class="footer-icon-link"><i class="fa-brands fa-facebook-f footer-icon"></i></a>
        <a class="footer-icon-link"><i class="fa-brands fa-instagram footer-icon"></i></a>
        <a class="footer-icon-link"><i class="fa-brands fa-twitter footer-icon"></i></a>
        <a class="footer-icon-link"><i class="fa-brands fa-google footer-icon"></i></a>
        <a class="footer-icon-link"><i class="fa-brands fa-linkedin footer-icon"></i></a>
        <div>© @DateTime.Now.Year Fixxo. All Rights Reserved</div>
    </div>
</footer>

WebApp/Views/Shared/Partials/_FooterInfo.cshtml
<div class="container mt-5">
    <hr />

    <div class="container text-center mt-5 mb-5">
        <div class="row">
            <div class="col-lg-3">
                <a class="information-link"><i class="fa-light fa-phone-flip icon-information"></i></a>
                <h5 class="name">Customer Support</h5>
                <p>Village did removed enjoyed explain talking.</p>
            </div>

            <div class="col-lg-3">
                <a class="information-link"><i class="fa-sharp fa-solid fa-lock-keyhole icon-information"></i></a>
                <h5 class="name">Secured Payment</h5>
                <p>Village did removed enjoyed explain talking.</p>
            </div>

            <div class="col-lg-3">
                <a class="information-link"><i class="fa-regular fa-truck fa-circle icon-information"></i></a>
                <h5 class="name">Free Home Delivery</h5>
                <p>Village did removed enjoyed explain talking.</p>
            </div>

            <div class="col-lg-3">
                <a class="information-link"><i class="fa-regular fa-truck icon-information"></i></a>
                <h5 class="name">30 Day Returns</h5>
                <p>Village did removed enjoyed explain talking.</p>
            </div>
        </div>
</div>
</div>

WebApp/Views/Shared/Partials/_Header.cshtml
<header>
    <div class="container">
        <a id="logotype" asp-controller="Home" asp-action="Index">Fixxo.</a>

        <div id="menu" class="hide">
            <nav class="menu-links links">
                <a class="link" asp-controller="Home" asp-action="Index">Home</a>
                <a class="link" asp-controller="Contacts" asp-action="Index">Contacts</a>
            </nav>

            <nav class="menu-icons icons">
                <a class="link" asp-controller="Home" asp-action="Index"><i class="fa-regular fa-search"></i></a>
                <a class="link" asp-controller="Home" asp-action="Index"><i class="fa-regular fa-code-compare"></i></a>
                <a class="link" asp-controller="Home" asp-action="Index"><i class="fa-regular fa-heart"></i></a>
                <a class="link" asp-controller="Home" asp-action="Index"><i class="fa-regular fa-bag-shopping"></i></a>
                <a class="link ms-5" asp-controller="Account" asp-action="Index"><i class="fa-regular fa-user"></i></a>
            </nav>
        </div>

        <div id="toggle-icon" class="icons">
            <button class="link" id="hamburger" data-option="toggle" data-target="#menu">
                <i class="fa-regular fa-bars"></i>
            </button>
        </div>
    </div>
</header>

WebApp/Views/Shared/Partials/_LocalPageNavPartial.cshtml
@model string
<div class="container local-page-nav-items">
    <a asp-controller="Home" asp-action="Index" class="home-page-link">Home > </a>
    <span class="current-page-text">@Model</span>
</div>

WebApp/Views/Shared/Partials/_NavPath.cshtml
@model string
<div class="container local-page-nav-items">
    <a asp-controller="Home" asp-action="Index" class="home-page-link">Home > </a>
    <span class="current-page-text">@Model</span>
</div>

WebApp/Views/Shared/Partials/_NewProducts.cshtml
@model IEnumerable<ProductDTO>
<section class="collection-twocolumns">
    <div class="column bg-gray">
        <div class="content">
            <h1>2 FOR USD $29</h1>
            <button class="btn-white">NEW PRODUCTS</button>
        </div>
    </div>
    <div class="column item-collection">
        @foreach (var item in Model)
        {
            <partial name="~/Views/Shared/Partials/_CollectionItem.cshtml" model="item" />
        }
    </div>
</section>

WebApp/Views/Shared/Partials/_PopularProducts.cshtml
@model IEnumerable<ProductDTO>
<section class="collection-twocolumns">
    <div class="column item-collection">
        @foreach (var item in Model)
        {
            <partial name="~/Views/Shared/Partials/_CollectionItem.cshtml" model="item" />
        }
    </div>
    <div class="column bg-gray">
        <div class="content">
            <h1>2 FOR USD $29</h1>
            <button class="btn-white">POPULAR PRODUCTS</button>
        </div>
    </div>
</section>

WebApp/Views/Shared/Partials/_SpecialOffer.cshtml
<div class="offer-grid container-fluid">
    <img id="office-style" src="~/images/office-style.png" alt="" />

    <div class="offer">
        <div class="red-border">
            <div class="content">
                <h1>50% Offer</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, ipsam quo voluptatum facere iure fuga. Necessitatibus quasi voluptatem delectus nam?</p>
                <button class="btn-white">FLASH SALE</button>
            </div>
        </div>
    </div>
    <img id="party-style" src="~/images/party-style.png" alt="" />
</div>

WebApp/Views/Shared/Partials/_StarRating.cshtml
@model int

@{
    int maxStars = 5;
    var stars = Enumerable.Range(1, maxStars).Select(i => i <= Model
        ? "fa-solid fa-star"
        : "fa-regular fa-star").ToList();
}

<div class="star-rating">
    @for (int i = 0; i < maxStars; i++)
    {
        <i class="fa-sharp @stars[i]"></i>
    }
</div>

WebApp/Views/Shared/Partials/_TopSelling.cshtml
<section class="collection-twocolumns">
    <div class="column item-collection">
        @for (int i = 0; i < 6; i++)
        {
            <partial name="~/Views/Shared/Partials/_CollectionItem.cshtml" />
        }
    </div>
    <div class="column bg-gray">
        <div class="content">
            <h1>2 FOR USD $29</h1>
            <button class="btn-white">POPULAR PRODUCTS</button>
        </div>
    </div>
</section>

WebApp/Views/Shared/Partials/_UpToSell.cshtml
<div class="offer-grid container-fluid">
    <img id="office-style" src="~/images/office-style.png" alt="" />

    <div class="offer">
        <div class="red-border">
            <div class="content">
                <h1>50% Offer</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, ipsam quo voluptatum facere iure fuga. Necessitatibus quasi voluptatem delectus nam?</p>
                <button class="btn-white">FLASH SALE</button>
            </div>
        </div>
    </div>
    <img id="party-style" src="~/images/party-style.png" alt="" />
</div>